CREATE TABLE IF NOT EXISTS CONSUMPTIONS.FACT_CONSUMPTIONS (
    "ID" VARCHAR(255) NOT NULL PRIMARY KEY,
    "YEAR" INT,
    "SECTOR_ID" INT NOT NULL,
    "STRATUM" INT,
    "CONSUMPTION" FLOAT,
    "RATE" FLOAT NOT NULL,
    "CALCULATED_RATE" FLOAT NOT NULL,
    CONSTRAINT fk_sector_id FOREIGN KEY ("SECTOR_ID") REFERENCES DIM_SECTORS("SECTOR_ID")
);